<?php
/**
 * Dynamic upload limits configuration
 * This file is auto-generated by the application settings
 * Do not edit manually
 */

// Default values (will be overridden by Setting controller)
$upload_limits = [
    'upload_max_filesize' => '1000M',
    'post_max_size'      => '1200M',
    'max_execution_time'  => 1800,
    'max_input_time'      => 1800,
    'memory_limit'        => '1024M',
];
