<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class CutiSmokeTestSeeder extends Seeder
{
    public function run()
    {
        $today = date('Y-m-d');

        $data = [
            [
                'nomor_surat'           => '01/CUTI/ST/2026',
                'tanggal_pengajuan'     => $today,
                'pegawai_id'            => 1,
                'nama'                  => 'Muhammad Yudi Prasetya, ST',
                'nip'                   => '198002142014121002',
                'jabatan'               => 'Kepala Satuan Kerja Pelaksanaan Prasarana Strategis Riau',
                'masa_kerja'            => '11 Tahun 7 Bulan',
                'unit_kerja'            => 'Satuan Kerja Pelaksanaan Prasarana Strategis Riau',
                'jenis_cuti'            => 'Cuti Tahunan',
                'alasan_cuti'           => 'Mengikuti kegiatan keluarga dan urusan pribadi di luar kota.',
                'lama_cuti_jumlah'      => 3,
                'lama_cuti_satuan'      => 'Hari',
                'tanggal_mulai'         => '2026-08-03',
                'tanggal_selesai'       => '2026-08-05',
                'alamat_selama_cuti'    => 'Jl. Sudirman No. 45, Pekanbaru',
                'telepon'               => '081268112233',
                'catatan_cuti_n2'       => 0,
                'catatan_cuti_n1'       => 0,
                'catatan_cuti_n'        => 9,
                'catatan_cuti_keterangan' => 'Sisa cuti tahun 2026',
                'atasan_nama'           => 'Muhammad Yudi Prasetya, ST',
                'atasan_nip'            => '198002142014121002',
                'atasan_jabatan'        => 'Kepala Satuan Kerja Pelaksanaan Prasarana Strategis Riau',
                'pejabat_nama'          => 'Ir. Agung Hari Prabowo, M.T',
                'pejabat_nip'           => '196910301998031005',
                'pejabat_jabatan'       => 'Plt. Sekretariat Direktorat Jenderal Prasarana Strategis',
                'pertimbangan_atasan'   => 'Pending',
                'keputusan_pejabat'     => 'Pending',
                'status'                => 'pending',
                'created_by'            => 'admin',
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ],
            [
                'nomor_surat'           => '02/CUTI/ST/2026',
                'tanggal_pengajuan'     => $today,
                'pegawai_id'            => 2,
                'nama'                  => 'Nurhidayat Nugraha',
                'nip'                   => '199012212018021001',
                'jabatan'               => 'PPK Prasarana Strategis',
                'masa_kerja'            => '8 Tahun 5 Bulan',
                'unit_kerja'            => 'Satuan Kerja Pelaksanaan Prasarana Strategis Riau',
                'jenis_cuti'            => 'Cuti Sakit',
                'alasan_cuti'           => 'Istirahat rawat jalan sesuai surat keterangan dokter Rumah Sakit.',
                'lama_cuti_jumlah'      => 2,
                'lama_cuti_satuan'      => 'Hari',
                'tanggal_mulai'         => '2026-08-06',
                'tanggal_selesai'       => '2026-08-07',
                'alamat_selama_cuti'    => 'Jl. HR Soebrantas No. 12, Pekanbaru',
                'telepon'               => '081371998877',
                'catatan_cuti_n2'       => 0,
                'catatan_cuti_n1'       => 0,
                'catatan_cuti_n'        => 12,
                'catatan_cuti_keterangan' => 'Disertai Surat Keterangan Dokter',
                'atasan_nama'           => 'Muhammad Yudi Prasetya, ST',
                'atasan_nip'            => '198002142014121002',
                'atasan_jabatan'        => 'Kepala Satuan Kerja Pelaksanaan Prasarana Strategis Riau',
                'pejabat_nama'          => 'Ir. Agung Hari Prabowo, M.T',
                'pejabat_nip'           => '196910301998031005',
                'pejabat_jabatan'       => 'Plt. Sekretariat Direktorat Jenderal Prasarana Strategis',
                'pertimbangan_atasan'   => 'Disetujui',
                'keputusan_pejabat'     => 'Disetujui',
                'status'                => 'disetujui',
                'created_by'            => 'admin',
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ],
            [
                'nomor_surat'           => '03/CUTI/ST/2026',
                'tanggal_pengajuan'     => $today,
                'pegawai_id'            => 3,
                'nama'                  => 'Hendra, S.T.',
                'nip'                   => '197709092009021001',
                'jabatan'               => 'Kasatker / Pejabat Teknis',
                'masa_kerja'            => '17 Tahun 3 Bulan',
                'unit_kerja'            => 'Satuan Kerja Pelaksanaan Prasarana Strategis Riau',
                'jenis_cuti'            => 'Cuti Besar',
                'alasan_cuti'           => 'Menunaikan ibadah umroh dan kegiatan keagamaan keluarga.',
                'lama_cuti_jumlah'      => 1,
                'lama_cuti_satuan'      => 'Bulan',
                'tanggal_mulai'         => '2026-09-01',
                'tanggal_selesai'       => '2026-09-30',
                'alamat_selama_cuti'    => 'Makkah & Madinah Al-Munawwarah',
                'telepon'               => '08117500123',
                'catatan_cuti_n2'       => 0,
                'catatan_cuti_n1'       => 0,
                'catatan_cuti_n'        => 0,
                'catatan_cuti_keterangan' => 'Pengajuan Cuti Besar',
                'atasan_nama'           => 'Muhammad Yudi Prasetya, ST',
                'atasan_nip'            => '198002142014121002',
                'atasan_jabatan'        => 'Kepala Satuan Kerja Pelaksanaan Prasarana Strategis Riau',
                'pejabat_nama'          => 'Ir. Agung Hari Prabowo, M.T',
                'pejabat_nip'           => '196910301998031005',
                'pejabat_jabatan'       => 'Plt. Sekretariat Direktorat Jenderal Prasarana Strategis',
                'pertimbangan_atasan'   => 'Disetujui',
                'keputusan_pejabat'     => 'Disetujui',
                'status'                => 'disetujui',
                'created_by'            => 'admin',
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ],
            [
                'nomor_surat'           => '04/CUTI/ST/2026',
                'tanggal_pengajuan'     => $today,
                'pegawai_id'            => 4,
                'nama'                  => 'KH. Sri Handayani',
                'nip'                   => '198204022014122001',
                'jabatan'               => 'Staf Administrasi / Pengelola Keuangan',
                'masa_kerja'            => '11 Tahun 5 Bulan',
                'unit_kerja'            => 'Satuan Kerja Pelaksanaan Prasarana Strategis Riau',
                'jenis_cuti'            => 'Cuti Melahirkan',
                'alasan_cuti'           => 'Persalinan anak ketiga dan masa pemulihan paska persalinan.',
                'lama_cuti_jumlah'      => 3,
                'lama_cuti_satuan'      => 'Bulan',
                'tanggal_mulai'         => '2026-08-10',
                'tanggal_selesai'       => '2026-11-10',
                'alamat_selama_cuti'    => 'Jl. Arifin Ahmad No. 88, Pekanbaru',
                'telepon'               => '082169554433',
                'catatan_cuti_n2'       => 0,
                'catatan_cuti_n1'       => 0,
                'catatan_cuti_n'        => 12,
                'catatan_cuti_keterangan' => 'Cuti Melahirkan Anak ke-3',
                'atasan_nama'           => 'Muhammad Yudi Prasetya, ST',
                'atasan_nip'            => '198002142014121002',
                'atasan_jabatan'        => 'Kepala Satuan Kerja Pelaksanaan Prasarana Strategis Riau',
                'pejabat_nama'          => 'Ir. Agung Hari Prabowo, M.T',
                'pejabat_nip'           => '196910301998031005',
                'pejabat_jabatan'       => 'Plt. Sekretariat Direktorat Jenderal Prasarana Strategis',
                'pertimbangan_atasan'   => 'Disetujui',
                'keputusan_pejabat'     => 'Disetujui',
                'status'                => 'disetujui',
                'created_by'            => 'admin',
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ],
            [
                'nomor_surat'           => '05/CUTI/ST/2026',
                'tanggal_pengajuan'     => $today,
                'pegawai_id'            => 5,
                'nama'                  => 'Havezt, A.Md.',
                'nip'                   => '199707162020121001',
                'jabatan'               => 'Pengelola Data Dan Informasi',
                'masa_kerja'            => '5 Tahun 5 Bulan',
                'unit_kerja'            => 'Satuan Kerja Pelaksanaan Prasarana Strategis Riau',
                'jenis_cuti'            => 'Cuti Karena Alasan Penting',
                'alasan_cuti'           => 'Mendampingi orang tua yang sedang dalam perawatan medis darurat.',
                'lama_cuti_jumlah'      => 4,
                'lama_cuti_satuan'      => 'Hari',
                'tanggal_mulai'         => '2026-08-12',
                'tanggal_selesai'       => '2026-08-15',
                'alamat_selama_cuti'    => 'Jl. Tuanku Tambusai No. 102, Pekanbaru',
                'telepon'               => '085278119900',
                'catatan_cuti_n2'       => 0,
                'catatan_cuti_n1'       => 0,
                'catatan_cuti_n'        => 8,
                'catatan_cuti_keterangan' => 'Alasan penting keluarga',
                'atasan_nama'           => 'Muhammad Yudi Prasetya, ST',
                'atasan_nip'            => '198002142014121002',
                'atasan_jabatan'        => 'Kepala Satuan Kerja Pelaksanaan Prasarana Strategis Riau',
                'pejabat_nama'          => 'Ir. Agung Hari Prabowo, M.T',
                'pejabat_nip'           => '196910301998031005',
                'pejabat_jabatan'       => 'Plt. Sekretariat Direktorat Jenderal Prasarana Strategis',
                'pertimbangan_atasan'   => 'Pending',
                'keputusan_pejabat'     => 'Pending',
                'status'                => 'pending',
                'created_by'            => 'admin',
                'created_at'            => date('Y-m-d H:i:s'),
                'updated_at'            => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('surat_cuti')->insertBatch($data);
    }
}
