<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class BaselineCurrentSchema extends Migration
{
    private array $createStatements = array (
  0 => 'CREATE TABLE `menu_akses` (
  `role_id` int(11) unsigned NOT NULL,
  `menu_id` varchar(255) NOT NULL,
  `FiturAdd` bit(1) DEFAULT b\'0\',
  `FiturEdit` bit(1) DEFAULT b\'0\',
  `FiturDelete` bit(1) DEFAULT b\'0\',
  `FiturExport` bit(1) DEFAULT b\'0\',
  `FiturImport` bit(1) DEFAULT b\'0\',
  `FiturApproval` bit(1) DEFAULT b\'0\',
  PRIMARY KEY (`role_id`,`menu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  1 => 'CREATE TABLE `menu_lv1` (
  `id` varchar(11) NOT NULL,
  `label` varchar(255) NOT NULL,
  `link` varchar(255) DEFAULT NULL,
  `icon` varchar(255) NOT NULL,
  `old_icon` varchar(255) DEFAULT NULL,
  `ordering` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  2 => 'CREATE TABLE `menu_lv2` (
  `id` varchar(255) NOT NULL,
  `label` varchar(255) NOT NULL,
  `link` varchar(255) DEFAULT NULL,
  `icon` varchar(255) NOT NULL,
  `header` varchar(255) NOT NULL,
  `ordering` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  3 => 'CREATE TABLE `menu_lv3` (
  `id` varchar(255) NOT NULL,
  `label` varchar(255) NOT NULL,
  `icon` varchar(255) NOT NULL,
  `link` varchar(255) DEFAULT NULL,
  `header` varchar(255) NOT NULL,
  `ordering` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  4 => 'CREATE TABLE `mst_kabupaten` (
  `kode_provinsi` varchar(10) NOT NULL,
  `kode_kabupaten` varchar(10) NOT NULL,
  `nama_kabupaten` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`kode_provinsi`,`kode_kabupaten`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  5 => 'CREATE TABLE `mst_kecamatan` (
  `kode_provinsi` varchar(10) NOT NULL,
  `kode_kabupaten` varchar(10) NOT NULL,
  `kode_kecamatan` varchar(10) NOT NULL,
  `nama_kecamatan` varchar(255) DEFAULT NULL,
  `kategori_konflik` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`kode_provinsi`,`kode_kabupaten`,`kode_kecamatan`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  6 => 'CREATE TABLE `trn_kontrak_ki_pekerjaan_baphp` (
  `id` int(11) NOT NULL COMMENT \'Primary Key\',
  `id_kontrak_paket` varchar(255) DEFAULT NULL,
  `pekerjaan` varchar(255) DEFAULT NULL,
  `is_all_personel` tinyint(1) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL COMMENT \'Create Time\'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;',
  7 => 'CREATE TABLE `trn_kontrak_paket` (
  `id` int(11) unsigned NOT NULL,
  `nama_paket` varchar(255) DEFAULT NULL,
  `kop_surat_id` int(11) unsigned DEFAULT NULL,
  `created_by` varchar(255) DEFAULT NULL,
  `created_date` date DEFAULT current_timestamp(),
  `laporan` text DEFAULT NULL,
  `hasil` text DEFAULT NULL,
  `tugas_tanggung_jawab` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;',
  8 => 'CREATE TABLE `trn_survey_sekolah` (
  `id` int(10) unsigned NOT NULL,
  `npsn` varchar(255) DEFAULT NULL,
  `periode` date DEFAULT NULL,
  `emis_jumlah_siswa` varchar(255) DEFAULT NULL,
  `survey_jumlah_siswa` varchar(255) DEFAULT NULL,
  `survey_tingat_kerusakan` double DEFAULT NULL,
  `survey_klasifikasi_kerusakan` varchar(255) DEFAULT NULL,
  `status_lahan` varchar(255) DEFAULT NULL,
  `status_penanganan` varchar(255) DEFAULT NULL,
  `ekspos_tingkat_kerusakan` double DEFAULT NULL,
  `ekspos_klasifikasi_kerusakan` varchar(255) DEFAULT NULL,
  `ekspos_status` varchar(255) DEFAULT NULL,
  `created_by` varchar(255) NOT NULL,
  `created_date` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;',
  9 => 'CREATE TABLE `access_roles` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `label` varchar(100) NOT NULL,
  `role_key` varchar(100) NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `role_key` (`role_key`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  10 => 'CREATE TABLE `app_settings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `app_name` varchar(190) NOT NULL DEFAULT \'PLN EPM-Digi\',
  `primary_color` varchar(7) NOT NULL DEFAULT \'#0a66c2\',
  `sidebar_bg_color` varchar(7) DEFAULT \'#2F3A45\',
  `sidebar_text_color` varchar(7) DEFAULT \'#C2CBD5\',
  `sidebar_active_bg_color` varchar(7) DEFAULT \'#0A66C2\',
  `sidebar_active_text_color` varchar(7) DEFAULT \'#FFFFFF\',
  `app_logo_url` varchar(255) DEFAULT NULL,
  `login_background_url` varchar(255) DEFAULT NULL,
  `auto_logout_minutes` int(11) NOT NULL DEFAULT 60,
  `preloader_duration_ms` int(11) DEFAULT 500,
  `updated_at` datetime DEFAULT NULL,
  `updated_by` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  11 => 'CREATE TABLE `articles` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `summary` text NOT NULL,
  `content` longtext NOT NULL,
  `category` varchar(100) NOT NULL DEFAULT \'Umum\',
  `image_url` varchar(255) DEFAULT NULL,
  `is_published` tinyint(1) NOT NULL DEFAULT 1,
  `published_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  12 => 'CREATE TABLE `audit_histories` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `action_type` varchar(20) NOT NULL,
  `module_path` varchar(255) NOT NULL,
  `table_name` varchar(100) DEFAULT NULL,
  `record_id` varchar(80) DEFAULT NULL,
  `user_id` int(11) unsigned DEFAULT NULL,
  `username` varchar(120) DEFAULT NULL,
  `role` varchar(120) DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `request_data_json` longtext DEFAULT NULL,
  `before_data_json` longtext DEFAULT NULL,
  `after_data_json` longtext DEFAULT NULL,
  `happened_at` datetime NOT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `action_type` (`action_type`),
  KEY `happened_at` (`happened_at`),
  KEY `table_name_record_id` (`table_name`,`record_id`)
) ENGINE=InnoDB AUTO_INCREMENT=57 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  13 => 'CREATE TABLE `auth_accounts` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `login_identifier` varchar(100) NOT NULL,
  `source_type` varchar(20) NOT NULL DEFAULT \'users\',
  `source_id` int(11) unsigned NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `role` varchar(50) NOT NULL DEFAULT \'editor\',
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_auth_accounts_login_identifier` (`login_identifier`),
  UNIQUE KEY `uq_auth_accounts_source` (`source_type`,`source_id`),
  KEY `is_active` (`is_active`),
  KEY `role` (`role`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  14 => 'CREATE TABLE `events` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `summary` text NOT NULL,
  `content` longtext NOT NULL,
  `event_date` date DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `image_url` varchar(255) DEFAULT NULL,
  `is_published` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  15 => 'CREATE TABLE `home_settings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `hero_title` varchar(255) NOT NULL,
  `hero_subtitle` text NOT NULL,
  `about_intro` text NOT NULL,
  `official_name` varchar(200) NOT NULL DEFAULT \'Satker PPS Kementerian PU\',
  `logo_url` varchar(255) DEFAULT NULL,
  `contact_email` varchar(190) DEFAULT NULL,
  `contact_phone` varchar(100) DEFAULT NULL,
  `contact_address` text DEFAULT NULL,
  `contact_map_url` varchar(255) DEFAULT NULL,
  `instagram_profile_url` varchar(255) DEFAULT NULL,
  `instagram_post_urls` longtext DEFAULT NULL,
  `default_event_image` varchar(255) DEFAULT NULL,
  `default_article_image` varchar(255) DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `updated_by` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  16 => 'CREATE TABLE `home_slides` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `image_url` varchar(255) NOT NULL,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  17 => 'CREATE TABLE `kegiatan_lapangan` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(190) NOT NULL,
  `activity_date` date DEFAULT NULL,
  `location` varchar(190) NOT NULL,
  `created_by` varchar(190) NOT NULL,
  `created_by_user_id` int(11) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `activity_date` (`activity_date`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  18 => 'CREATE TABLE `kegiatan_lapangan_photos` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `activity_id` int(11) unsigned NOT NULL,
  `photo_path` varchar(255) NOT NULL,
  `photo_name` varchar(255) DEFAULT NULL,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `activity_id` (`activity_id`),
  KEY `sort_order` (`sort_order`)
) ENGINE=InnoDB AUTO_INCREMENT=82 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  19 => 'CREATE TABLE `kegiatan_lapangan_shares` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `activity_id` int(11) unsigned NOT NULL,
  `share_token` varchar(128) NOT NULL,
  `expires_at` datetime DEFAULT NULL,
  `created_by_user_id` int(11) unsigned DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_kegiatan_lapangan_share_activity` (`activity_id`),
  UNIQUE KEY `uniq_kegiatan_lapangan_share_token` (`share_token`),
  CONSTRAINT `kegiatan_lapangan_shares_activity_id_foreign` FOREIGN KEY (`activity_id`) REFERENCES `kegiatan_lapangan` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  20 => 'CREATE TABLE `kop_surat` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(150) NOT NULL,
  `image_url` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  21 => 'CREATE TABLE `laporan_harian_reports` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `sekolah_id` int(11) unsigned DEFAULT NULL,
  `report_date` date NOT NULL,
  `sections_json` longtext DEFAULT NULL,
  `personil_pekerja` varchar(150) DEFAULT NULL,
  `personil_tukang` varchar(150) DEFAULT NULL,
  `cuaca_cerah` varchar(150) DEFAULT NULL,
  `cuaca_hujan` varchar(150) DEFAULT NULL,
  `latitude` decimal(10,7) DEFAULT NULL,
  `longitude` decimal(10,7) DEFAULT NULL,
  `input_device` varchar(20) DEFAULT NULL,
  `photo_paths_json` longtext DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `title_id` (`sekolah_id`),
  KEY `report_date` (`report_date`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  22 => 'CREATE TABLE `laporan_mingguan_histories` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `laporan_mingguan_id` int(11) unsigned NOT NULL,
  `sekolah_id` int(11) unsigned DEFAULT NULL,
  `period_start` date DEFAULT NULL,
  `period_end` date DEFAULT NULL,
  `description` text DEFAULT NULL,
  `file_path` varchar(255) DEFAULT NULL,
  `file_name` varchar(255) DEFAULT NULL,
  `changed_by` varchar(100) DEFAULT NULL,
  `changed_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `laporan_mingguan_id` (`laporan_mingguan_id`),
  KEY `changed_at` (`changed_at`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  23 => 'CREATE TABLE `laporan_mingguan_reports` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `sekolah_id` int(11) unsigned DEFAULT NULL,
  `period_start` date NOT NULL,
  `period_end` date NOT NULL,
  `description` text DEFAULT NULL,
  `file_path` varchar(255) NOT NULL,
  `file_name` varchar(255) NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `title_id` (`sekolah_id`),
  KEY `period_start` (`period_start`),
  KEY `period_end` (`period_end`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  24 => 'CREATE TABLE `laporan_sekolah` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(150) NOT NULL,
  `ordering` int(11) NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  25 => 'CREATE TABLE `login_histories` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `attempted_at` datetime NOT NULL,
  `is_success` tinyint(1) NOT NULL DEFAULT 0,
  `failure_reason` varchar(190) DEFAULT NULL,
  `username_input` varchar(120) DEFAULT NULL,
  `user_id` int(11) unsigned DEFAULT NULL,
  `full_name` varchar(150) DEFAULT NULL,
  `role` varchar(120) DEFAULT NULL,
  `account_active` tinyint(1) DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `http_method` varchar(10) DEFAULT NULL,
  `request_path` varchar(255) DEFAULT NULL,
  `referer` varchar(255) DEFAULT NULL,
  `session_id` varchar(128) DEFAULT NULL,
  `request_payload_json` longtext DEFAULT NULL,
  `server_context_json` longtext DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `attempted_at` (`attempted_at`),
  KEY `is_success` (`is_success`),
  KEY `username_input` (`username_input`),
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=380 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  26 => 'CREATE TABLE `mst_jabatan` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `jabatan` varchar(1000) NOT NULL,
  `jenis_jabatan` varchar(50) NOT NULL,
  `deskripsi_jabatan` text DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_by` varchar(255) DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `updated_by` varchar(255) DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `jabatan` (`jabatan`(768)),
  KEY `is_active` (`is_active`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  27 => 'CREATE TABLE `mst_kelurahan` (
  `kode_provinsi` varchar(10) NOT NULL,
  `kode_kabupaten` varchar(10) NOT NULL,
  `kode_kecamatan` varchar(10) NOT NULL,
  `kode_kelurahan` varchar(10) NOT NULL,
  `nama_kelurahan` varchar(255) DEFAULT NULL,
  `kategori_konflik` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`kode_provinsi`,`kode_kabupaten`,`kode_kecamatan`,`kode_kelurahan`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  28 => 'CREATE TABLE `mst_map_type` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `map_name` varchar(50) DEFAULT NULL,
  `map_script` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  29 => 'CREATE TABLE `mst_pegawai` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `nip` varchar(30) NOT NULL,
  `nama` varchar(150) NOT NULL,
  `jenis_pegawai` varchar(20) DEFAULT \'pns\',
  `foto` varchar(255) DEFAULT NULL,
  `jabatan_utama_id` int(11) unsigned DEFAULT NULL,
  `jabatan_perbendaharaan_id` int(11) unsigned DEFAULT NULL,
  `eselon` varchar(50) DEFAULT NULL,
  `golongan` varchar(50) DEFAULT NULL,
  `masa_kerja` varchar(50) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_by` varchar(255) DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `updated_by` varchar(255) DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `nip` (`nip`),
  KEY `is_active` (`is_active`),
  KEY `jabatan_utama_id` (`jabatan_utama_id`),
  KEY `jabatan_perbendaharaan_id` (`jabatan_perbendaharaan_id`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  30 => 'CREATE TABLE `mst_provinsi` (
  `kode_provinsi` varchar(10) NOT NULL,
  `nama_provinsi` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`kode_provinsi`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  31 => 'CREATE TABLE `mst_sekolah` (
  `npsn` bigint(20) NOT NULL,
  `nama` varchar(255) DEFAULT NULL,
  `jenis` varchar(255) DEFAULT NULL,
  `nsm` bigint(20) DEFAULT NULL,
  `kabupaten` varchar(255) DEFAULT NULL,
  `kecamatan` varchar(255) DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `created_by` varchar(255) DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `updated_by` varchar(255) DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  PRIMARY KEY (`npsn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  32 => 'CREATE TABLE `trn_kontrak_ki` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nomor_kontrak` varchar(255) DEFAULT NULL,
  `tanggal_kontrak` date DEFAULT NULL,
  `paket` varchar(255) DEFAULT NULL,
  `kode_personil` varchar(255) DEFAULT NULL,
  `nama` varchar(255) DEFAULT NULL,
  `alamat` varchar(255) DEFAULT NULL,
  `nik` bigint(20) DEFAULT NULL,
  `npwp` varchar(255) DEFAULT NULL,
  `jabatan` varchar(255) DEFAULT NULL,
  `durasi_pelaksanaan` varchar(255) DEFAULT NULL,
  `nomor_dipa` varchar(255) DEFAULT NULL,
  `tanggal_dipa` date DEFAULT NULL,
  `mata_anggaran` varchar(255) DEFAULT NULL,
  `nomor_surat_undangan_pengadaan` varchar(255) DEFAULT NULL,
  `tanggal_surat_undangan_pengadaan` date DEFAULT NULL,
  `nomor_surat_berita_acara_pengadaan` varchar(255) DEFAULT NULL,
  `tanggal_surat_berita_acara_pengadaan` date DEFAULT NULL,
  `nomor_surat_penawaran` varchar(255) DEFAULT NULL,
  `tanggal_surat_penawaran` date DEFAULT NULL,
  `nomor_undangan` varchar(255) DEFAULT NULL,
  `total_penawaran` bigint(20) DEFAULT NULL,
  `tanggal_awal` date DEFAULT NULL,
  `tanggal_akhir` date DEFAULT NULL,
  `created_date` date DEFAULT current_timestamp(),
  `created_by` varchar(255) DEFAULT NULL,
  `tahun_anggaran` int(11) DEFAULT NULL,
  `no_sppbj` varchar(255) DEFAULT NULL,
  `tanggal_sppbj` date DEFAULT NULL,
  `pejabat_ppk` varchar(255) DEFAULT NULL,
  `nip_pejabat_ppk` varchar(255) DEFAULT NULL,
  `kedudukan_pejabat_ppk` varchar(255) DEFAULT NULL,
  `nomor_surat_keputusan_menteri` varchar(255) DEFAULT NULL,
  `tanggal_surat_keputusan_menteri` date DEFAULT NULL,
  `nomor_perubahan_keputusan_menteri` varchar(255) DEFAULT NULL,
  `bank_nomor_rekening` varchar(255) DEFAULT NULL,
  `bank_nama` varchar(255) DEFAULT NULL,
  `bank_atas_nama` varchar(255) DEFAULT NULL,
  `bank_pembayaran` varchar(255) DEFAULT NULL,
  `kategori` varchar(255) DEFAULT NULL,
  `nomor_telefon_ki` varchar(255) DEFAULT NULL,
  `email_ki` varchar(255) DEFAULT NULL,
  `nominal_kontrak` bigint(20) DEFAULT NULL,
  `nominal_hps` bigint(20) DEFAULT NULL,
  `nomor_spmk` varchar(255) DEFAULT NULL,
  `nomor_baphp` varchar(255) DEFAULT NULL,
  `nomor_surat_permohonan` varchar(255) DEFAULT NULL,
  `tanggal_surat_permohonan` date DEFAULT NULL,
  `nama_pekerjaan` varchar(255) DEFAULT NULL,
  `jenis_pembayaran` varchar(255) DEFAULT NULL,
  `nomor_bast` varchar(255) DEFAULT NULL,
  `tanggal_spmk` date DEFAULT NULL,
  `pendidikan` varchar(255) DEFAULT NULL,
  `sertifikat` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unik` (`nomor_kontrak`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=3416 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;',
  33 => 'CREATE TABLE `trn_kontrak_simak_share` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `simak_id` int(11) unsigned NOT NULL,
  `share_token` varchar(255) NOT NULL,
  `expires_at` datetime DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_by` varchar(100) DEFAULT NULL,
  `created_date` date DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `updated_date` date DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_trn_kontrak_simak_share_simak_id` (`simak_id`),
  UNIQUE KEY `uniq_trn_kontrak_simak_share_token` (`share_token`),
  CONSTRAINT `trn_kontrak_simak_share_simak_id_foreign` FOREIGN KEY (`simak_id`) REFERENCES `trn_kontrak_simak` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  34 => 'CREATE TABLE `trn_kontrak_simak_verifikasi` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `simak_id` int(11) unsigned NOT NULL,
  `row_no` int(11) unsigned NOT NULL,
  `kode` varchar(50) DEFAULT NULL,
  `uraian` text DEFAULT NULL,
  `kelengkapan_dokumen` varchar(10) DEFAULT NULL,
  `verifikasi_ki` varchar(20) DEFAULT NULL,
  `keterangan` text DEFAULT NULL,
  `pic` varchar(255) DEFAULT NULL,
  `created_by` varchar(255) DEFAULT NULL,
  `created_date` date DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_by` varchar(255) DEFAULT NULL,
  `updated_date` date DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `simak_id_row_no` (`simak_id`,`row_no`),
  KEY `simak_id` (`simak_id`),
  KEY `row_no` (`row_no`),
  CONSTRAINT `trn_kontrak_simak_verifikasi_simak_id_foreign` FOREIGN KEY (`simak_id`) REFERENCES `trn_kontrak_simak` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  35 => 'CREATE TABLE `trn_kontrak_simak_verifikasi_dokumen` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `simak_id` int(11) unsigned NOT NULL,
  `row_no` int(11) unsigned NOT NULL,
  `kode` varchar(50) DEFAULT NULL,
  `uraian` text DEFAULT NULL,
  `kelengkapan_dokumen` varchar(10) DEFAULT NULL,
  `verifikasi_ki` varchar(20) DEFAULT NULL,
  `keterangan` text DEFAULT NULL,
  `pic` text DEFAULT NULL,
  `file_original_name` varchar(255) NOT NULL,
  `file_stored_name` varchar(255) NOT NULL,
  `file_relative_path` varchar(500) NOT NULL,
  `file_mime` varchar(120) DEFAULT NULL,
  `file_size` bigint(20) unsigned NOT NULL DEFAULT 0,
  `created_by` varchar(255) DEFAULT NULL,
  `created_date` date DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_by` varchar(255) DEFAULT NULL,
  `updated_date` date DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `simak_id` (`simak_id`),
  KEY `row_no` (`row_no`),
  KEY `simak_id_row_no` (`simak_id`,`row_no`),
  CONSTRAINT `trn_kontrak_simak_verifikasi_dokumen_simak_id_foreign` FOREIGN KEY (`simak_id`) REFERENCES `trn_kontrak_simak` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  36 => 'CREATE TABLE `trn_syarat_umum_kontrak_ki` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `paket_id` int(11) DEFAULT NULL,
  `jabatan_name` varchar(255) DEFAULT NULL,
  `laporan` text DEFAULT NULL,
  `laporan_modal` longtext DEFAULT NULL,
  `hasil` text DEFAULT NULL,
  `hasil_modal` longtext DEFAULT NULL,
  `tugas_tanggung_jawab` text DEFAULT NULL,
  `tugas_tanggung_jawab_modal` longtext DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;',
  37 => 'CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(100) NOT NULL,
  `full_name` varchar(150) NOT NULL,
  `role` varchar(50) NOT NULL DEFAULT \'editor\',
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `password_hash` varchar(255) NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  38 => 'CREATE TABLE `trn_kontrak_simak_add_on` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `simak_id` int(11) unsigned NOT NULL,
  `kategori_add_on` varchar(30) DEFAULT \'konstruksi_fisik\',
  `urutan` int(5) unsigned NOT NULL DEFAULT 1,
  `nilai_add_on` bigint(20) DEFAULT 0,
  `tanggal_add_on` date DEFAULT NULL,
  `created_by` varchar(255) DEFAULT NULL,
  `created_date` date DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_by` varchar(255) DEFAULT NULL,
  `updated_date` date DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `simak_id_urutan` (`simak_id`,`urutan`),
  KEY `simak_id` (`simak_id`),
  CONSTRAINT `trn_kontrak_simak_add_on_simak_id_foreign` FOREIGN KEY (`simak_id`) REFERENCES `trn_kontrak_simak` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  39 => 'CREATE TABLE `trn_kontrak_simak` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `satker` varchar(255) NOT NULL DEFAULT \'Perencanaan Prasarana Strategis\',
  `ppk_nama` varchar(150) NOT NULL,
  `ppk_nip` varchar(30) NOT NULL,
  `nama_paket` varchar(255) NOT NULL,
  `tahun_anggaran` varchar(20) NOT NULL,
  `penyedia` varchar(255) DEFAULT NULL,
  `penyedia_jasa_konsultansi` varchar(255) DEFAULT NULL,
  `nomor_kontrak` varchar(120) NOT NULL,
  `nilai_kontrak` bigint(20) DEFAULT 0,
  `nilai_kontrak_jasa_konsultansi` bigint(20) DEFAULT 0,
  `tahapan_pekerjaan` varchar(255) DEFAULT NULL,
  `tanggal_pemeriksaan` date DEFAULT NULL,
  `jenis_pekerjaan_jasa_konsultansi` varchar(100) DEFAULT NULL,
  `masa_pelaksanaan` varchar(20) DEFAULT NULL,
  `pagu_anggaran` bigint(20) DEFAULT 0,
  `metode_pemilihan` varchar(50) DEFAULT NULL,
  `created_by` varchar(255) DEFAULT NULL,
  `created_date` date DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_by` varchar(255) DEFAULT NULL,
  `updated_date` date DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `nomor_kontrak` (`nomor_kontrak`),
  KEY `ppk_nip` (`ppk_nip`),
  KEY `tahun_anggaran` (`tahun_anggaran`),
  KEY `tanggal_pemeriksaan` (`tanggal_pemeriksaan`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  40 => 'CREATE TABLE `trn_kontrak_simak_konsultasi` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `satker` varchar(255) NOT NULL DEFAULT \'Perencanaan Prasarana Strategis\',
  `ppk_nama` varchar(150) NOT NULL,
  `ppk_nip` varchar(30) NOT NULL,
  `jenis_pekerjaan_jasa_konsultansi` varchar(100) DEFAULT NULL COMMENT \'Perencanaan/Perancangan/Pengawasan/Manajemen Konstruksi/Lainnya\',
  `nama_paket` varchar(255) NOT NULL,
  `masa_pelaksanaan` varchar(50) DEFAULT NULL COMMENT \'SYC/MYC\',
  `tahun_anggaran` varchar(20) NOT NULL,
  `pagu_anggaran` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT \'Pagu anggaran dalam satuan nominal\',
  `penyedia` varchar(255) DEFAULT NULL,
  `nomor_kontrak` varchar(120) NOT NULL,
  `nilai_kontrak` decimal(18,2) NOT NULL DEFAULT 0.00,
  `metode_pemilihan` varchar(100) DEFAULT NULL COMMENT \'Pengadaan Langsung/Penunjukan Langsung/Seleksi\',
  `tahapan_pekerjaan` varchar(255) DEFAULT NULL,
  `tanggal_pemeriksaan` date DEFAULT NULL,
  `dokumen_adm_kontrak` tinyint(1) NOT NULL DEFAULT 0,
  `dokumen_adm_spmk` tinyint(1) NOT NULL DEFAULT 0,
  `dokumen_adm_baphp` tinyint(1) NOT NULL DEFAULT 0,
  `dokumen_adm_bast` tinyint(1) NOT NULL DEFAULT 0,
  `dokumen_adm_invoice` tinyint(1) NOT NULL DEFAULT 0,
  `kelengkapan_dokumen_administrasi` decimal(5,2) NOT NULL DEFAULT 0.00,
  `created_by` varchar(255) DEFAULT NULL,
  `created_date` date DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_by` varchar(255) DEFAULT NULL,
  `updated_date` date DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `nomor_kontrak` (`nomor_kontrak`),
  KEY `ppk_nip` (`ppk_nip`),
  KEY `tahun_anggaran` (`tahun_anggaran`),
  KEY `tanggal_pemeriksaan` (`tanggal_pemeriksaan`),
  KEY `jenis_pekerjaan_jasa_konsultansi` (`jenis_pekerjaan_jasa_konsultansi`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  41 => 'CREATE TABLE `trn_kontrak_simak_konsultasi_add_on` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `simak_id` int(11) unsigned NOT NULL,
  `kategori` varchar(100) DEFAULT NULL,
  `item_add_on` varchar(255) DEFAULT NULL,
  `nilai_add_on` decimal(18,2) NOT NULL DEFAULT 0.00,
  `tanggal_add_on` date DEFAULT NULL,
  `created_by` varchar(255) DEFAULT NULL,
  `created_date` date DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_by` varchar(255) DEFAULT NULL,
  `updated_date` date DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `simak_id` (`simak_id`),
  KEY `kategori` (`kategori`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  42 => 'CREATE TABLE `trn_kontrak_simak_konsultasi_share` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `simak_id` int(11) unsigned NOT NULL,
  `share_token` varchar(255) NOT NULL,
  `share_url` varchar(500) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `expires_at` datetime DEFAULT NULL,
  `created_by` varchar(255) DEFAULT NULL,
  `created_date` date DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_by` varchar(255) DEFAULT NULL,
  `updated_date` date DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `share_token` (`share_token`),
  KEY `simak_id` (`simak_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  43 => 'CREATE TABLE `trn_kontrak_simak_konsultasi_verifikasi` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `simak_id` int(11) unsigned NOT NULL,
  `row_no` int(11) unsigned NOT NULL,
  `kode` varchar(50) DEFAULT NULL,
  `uraian` text DEFAULT NULL,
  `kelengkapan_dokumen` varchar(10) DEFAULT NULL,
  `verifikasi_ki` varchar(20) DEFAULT NULL,
  `keterangan` text DEFAULT NULL,
  `pic` varchar(255) DEFAULT NULL,
  `created_by` varchar(255) DEFAULT NULL,
  `created_date` date DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_by` varchar(255) DEFAULT NULL,
  `updated_date` date DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `simak_id` (`simak_id`),
  KEY `simak_id_row_no` (`simak_id`,`row_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
  44 => 'CREATE TABLE `trn_kontrak_simak_konsultasi_verifikasi_dokumen` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `simak_id` int(11) unsigned NOT NULL,
  `row_no` int(11) unsigned DEFAULT NULL,
  `kode` varchar(50) DEFAULT NULL,
  `uraian` text DEFAULT NULL,
  `kelengkapan_dokumen` varchar(10) DEFAULT NULL,
  `verifikasi_ki` varchar(20) DEFAULT NULL,
  `keterangan` text DEFAULT NULL,
  `pic` text DEFAULT NULL,
  `file_original_name` varchar(255) DEFAULT NULL,
  `file_stored_name` varchar(255) DEFAULT NULL,
  `file_relative_path` varchar(500) DEFAULT NULL,
  `file_mime` varchar(120) DEFAULT NULL,
  `file_size` bigint(20) unsigned DEFAULT NULL,
  `nomor_dokumen` varchar(100) DEFAULT NULL,
  `tipe_dokumen` varchar(100) DEFAULT NULL,
  `nama_file` varchar(255) DEFAULT NULL,
  `file_path` varchar(500) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL COMMENT \'Lengkap/Belum Sesuai/Belum Verifikasi/Belum Ada\',
  `catatan` text DEFAULT NULL,
  `created_by` varchar(255) DEFAULT NULL,
  `created_date` date DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_by` varchar(255) DEFAULT NULL,
  `updated_date` date DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `simak_id` (`simak_id`),
  KEY `status` (`status`),
  KEY `idx_simak_konsultasi_verifikasi_dokumen_simak_row` (`simak_id`,`row_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;',
);

    private array $tableNames = array (
  0 => 'trn_kontrak_simak_konsultasi_verifikasi_dokumen',
  1 => 'trn_kontrak_simak_konsultasi_verifikasi',
  2 => 'trn_kontrak_simak_konsultasi_share',
  3 => 'trn_kontrak_simak_konsultasi_add_on',
  4 => 'trn_kontrak_simak_konsultasi',
  5 => 'trn_kontrak_simak',
  6 => 'trn_kontrak_simak_add_on',
  7 => 'users',
  8 => 'trn_syarat_umum_kontrak_ki',
  9 => 'trn_kontrak_simak_verifikasi_dokumen',
  10 => 'trn_kontrak_simak_verifikasi',
  11 => 'trn_kontrak_simak_share',
  12 => 'trn_kontrak_ki',
  13 => 'mst_sekolah',
  14 => 'mst_provinsi',
  15 => 'mst_pegawai',
  16 => 'mst_map_type',
  17 => 'mst_kelurahan',
  18 => 'mst_jabatan',
  19 => 'login_histories',
  20 => 'laporan_sekolah',
  21 => 'laporan_mingguan_reports',
  22 => 'laporan_mingguan_histories',
  23 => 'laporan_harian_reports',
  24 => 'kop_surat',
  25 => 'kegiatan_lapangan_shares',
  26 => 'kegiatan_lapangan_photos',
  27 => 'kegiatan_lapangan',
  28 => 'home_slides',
  29 => 'home_settings',
  30 => 'events',
  31 => 'auth_accounts',
  32 => 'audit_histories',
  33 => 'articles',
  34 => 'app_settings',
  35 => 'access_roles',
  36 => 'trn_survey_sekolah',
  37 => 'trn_kontrak_paket',
  38 => 'trn_kontrak_ki_pekerjaan_baphp',
  39 => 'mst_kecamatan',
  40 => 'mst_kabupaten',
  41 => 'menu_lv3',
  42 => 'menu_lv2',
  43 => 'menu_lv1',
  44 => 'menu_akses',
);

    public function up()
    {
        if ($this->createStatements === []) {
            return;
        }

        $this->db->query('SET FOREIGN_KEY_CHECKS = 0');
        foreach ($this->createStatements as $statement) {
            $this->db->query($statement);
        }
        $this->db->query('SET FOREIGN_KEY_CHECKS = 1');
    }

    public function down()
    {
        if ($this->tableNames === []) {
            return;
        }

        $this->db->query('SET FOREIGN_KEY_CHECKS = 0');
        foreach ($this->tableNames as $tableName) {
            $this->db->query('DROP TABLE IF EXISTS `' . $tableName . '`');
        }
        $this->db->query('SET FOREIGN_KEY_CHECKS = 1');
    }
}